### ISSUE TITLE
Each Art should be a gallerie independant 

### ISSUE THREAD

**Issue by bolom** [bolom/gilbertmarcel#13]
Upon clicking on a specific piece of art, the user should be presented with a curated series of images within the same category, rather than just a single image.

https://spinacms.com/docs/rendering-content/image-collection

**Comment by bolom** [comment]
Each item displayed is the cover image for a collection.

![Capture d’écran 2023-05-22 à 10 45 52](https://github.com/bolom/gilbertmarcel/assets/72155/5669ceba-f02a-410e-829d-74ae3cdd02df)

The three topmost elements highlight three distinct collections. When a user clicks on any of these items, they will be presented with a carousel filled with all the images from that specific collection.

Following this, the second section showcases a carousel that contains all the collections.

The third section features a highlight of another collection.

Both the topmost and bottom collections should also be represented within the carousel.
the collection in top and bottom shold be visible in the carrousel

make sense?

**Comment by dmytro-strukov** [comment]
@bolom Thank you for the explanation! Could you please provide samples of the HTML mockup of how it will be?

**Comment by bolom** [comment]
I've notice you created 3 sections in Spina
![Capture d’écran 2023-05-23 à 06 11 08](https://github.com/bolom/gilbertmarcel/assets/72155/08efbf7c-e097-478b-ad7f-077aae5b1168)

All the collections of images should be accessible in Art Gallery.

In Art Gallery the user should be able to do that,
1. Create a new folder for a new collection
2. Upload in this folder a new image with a description and title ( optional )

In this carrousel, the user will be able to see the first image for each collection, when he click on thumbnail, a carrousel will be displayed
![Capture d’écran 2023-05-23 à 06 13 37](https://github.com/bolom/gilbertmarcel/assets/72155/571a3369-0a5e-460a-8c24-9b13a8a007f0)

In Art Preview, the user should be able to select 3 collections who was already added in Art Gallery.

**Comment by bolom** [comment]
Also I've notice you don't really use Spina with  component, could you please improve your code with theme instead of create this kind of hack
https://github.com/bolom/gilbertmarcel/blob/master/app/views/default/pages/homepage.html.erb#L58

I've found this part very confusing, could you please use an ImageCollection 
https://spinacms.com/docs/rendering-content/image-collection

**Comment by bolom** [comment]
Closing this issue after review your code this morning. You didn't follow Spina CMS

Please focus on this

https://github.com/bolom/gilbertmarcel/issues/15
