### ISSUE TITLE
Add data in production

### ISSUE THREAD

**Issue by bolom** [bolom/gilbertmarcel#19]
We need to add the data in production

@EEUAAAIA 

http://gilbertmarcel.art/admin

temporary account

mathias@mathias.com

please update your password and email

https://3.basecamp.com/3097118/buckets/31704897/vaults/5870518265

https://www.loom.com/share/04fd6295f45b4d45a9279a5911f5f115?from_recorder=1&focus_title=1
![WhatsApp Image 2023-06-15 at 6 52 48 PM](https://github.com/bolom/gilbertmarcel/assets/72155/7b28bfd7-0be9-4c74-9ba0-954ed0b46634)
![WhatsApp Image 2023-06-15 at 7 02 40 PM](https://github.com/bolom/gilbertmarcel/assets/72155/1cb3e157-c16b-444b-a42e-6cbdf70360e7)
![WhatsApp Image 2023-06-15 at 7 04 17 PM](https://github.com/bolom/gilbertmarcel/assets/72155/86276dfb-bffa-47fa-9a64-d18050a98d35)
![WhatsApp Image 2023-06-15 at 7 05 24 PM (1)](https://github.com/bolom/gilbertmarcel/assets/72155/f6f08e09-4784-49b5-807c-1fff01dd26b8)
![WhatsApp Image 2023-06-15 at 7 05 24 PM (2)](https://github.com/bolom/gilbertmarcel/assets/72155/b99c4f6e-8f22-4537-8b16-4da0fa3a6073)
![WhatsApp Image 2023-06-15 at 7 05 24 PM](https://github.com/bolom/gilbertmarcel/assets/72155/e125e5f4-d88e-4dc3-ad2d-2824a4522d48)

**Comment by EEUAAAIA** [comment]
I update my email and my password. 
I added 2/3 pictures and title in production. 
I ask the customer what I want for the third picture.
