### ISSUE TITLE
NoMethodError in Spina::Admin::PagesController#index 

### ISSUE THREAD

**Issue by bolom** [bolom/gilbertmarcel#7]
After a fresh install,I've got this [error](url)
![Capture d’écran 2023-05-17 à 08 53 07](https://github.com/bolom/gilbertmarcel/assets/72155/a8307e14-b26f-4249-b183-8a934a3e46ad)

**Comment by dmytro-strukov** [comment]
@bolom You can fix it by running the following command ```rails spina:first_deploy```
